server:
    port: 8011
spring:
    application:
        name: zuulproxy
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        fetchRegistry: true
        registerWithEureka: true